config/routes.rb
Rails.application.routes.draw do
    
  root to: 'questions#index'
  resources :questions 
  resource :session, only: %i[new create destroy]
  resources :users, only: %i[new create]
  
  # post '/questions', to: 'questions#create'
  # patch '/questions/:id', to: 'questions#update'
  # delete '/questions/:id', to: 'questions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    private

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # skip_before_action :verify_authenticity_token
    before_action :set_question, only: %i[update show destroy edit]
    def create
      
      question = Question.create(question_params)

      flash[:notice] = 'New question create'

      redirect_to question_path(question), notice: 'Новый вопрос создан'
      
    end

    def update
     
      @question.update(question_params)
      redirect_to question_path(@question), notice: 'Вопрос отредактирован'
    end

    def destroy
      
      @question.destroy

      redirect_to "/questions", notice: 'Вопрос удален'
      
    end

    def show
     
    end

    def index
      @question = Question.new
      @questions = Question.all
    end

    def new
      @question = Question.new
    end

    def edit
      
    end

    private
    def question_params
      params.require(:question).permit(:body, :user_id)
    end

    def set_question
      @question = Question.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])



    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'Вы вошли на сайт!'
    else
      flash.now[:alert] = 'Неправильный email или пароль'

      render :new
      
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Вы вышли из аккаунта'
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    session[:current_time] = Time.now
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:name, :nickname, :email, :password)
    
    User.create(user_params)

    redirect_to root_path, notice: "Вы успешно зарегистрировались"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sklonenie(count, one, few, many)
        if count%100 < 15 && count%100 > 10
          return many
        else
          ostatok = count % 10
            if (ostatok == 1)
              return one
            end
  
            if (ostatok >= 2 && ostatok <= 4)
              return few
            end
  
            if (ostatok >= 5 && ostatok <= 9 || ostatok == 0)
              return many
            end
        end
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
  <div class="wrapper">
    <div class="navbar">
    <p class="title-sm text-bold"><%= link_to 'Ask Me', root_path %></p>
      <div>
        <% if current_user.present? %>
          <%= content_tag 'span', "@#{current_user.nickname}", class: 'mr-sm' %>
          <%= button_to 'Выйти', session_path, method: :delete %>

        <% else %>
           <%= link_to 'Регистрация', new_user_path, class: 'button button-yellow mr-sm' %>
           <%= link_to 'Вход', new_session_path, class: 'button button-yellow' %>

        <% end %>
      </div>
    </div>
    <% if flash[:notice].present? %>
     <p class="mb mt message message-notice"> <%= flash[:notice] %></p>
    <% elsif flash[:alert].present? %>
     <p class="mb mt message message-alert"> <%= flash[:alert] %></p>
    <% end %>



    <%= yield %>
  </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question do |form| %>
    <p><%= form.label :body, 'Text question' %></p>
    <p><%= form.text_area :body, rows: 5, class: "form-text-area" %></p>
    <p class="mt"><%= form.label :user_id %></p>
    <p><%= form.text_field :user_id, class: "form-text-field" %></p>
    <p class="mt">
        <%= form.submit 'Save', class: 'button button-main' %>
    </p>
<% end %>

app/views/questions/_question.html.erb
<div class="mb-sm mt-lg">
    <%= question.body %>
</div>


<div class="text-sm question-footer">
    <div class="text-gray">
        <%= l(question.created_at, format: :short) %>
    </div>

    <div>
        <%=  link_to fa_icon('pencil'), edit_question_path(question),
         title: "Изменить вопрос" %>
        
        <%= button_to fa_icon('trash-o'), question_path(question),
         method: :delete, title: "удалить вопрос" %>
    </div>

</div>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class='title-lg'>Редактирование вопроса <%= @question.id %></h2>
  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="container">
    <p class="mt">
        <%= link_to "Create new question", new_question_path, class: 'button button-main' %>
    </p>

    <p class="mt">
        <%= render 'form', question: @question %>  
    </p>

</div>

<div class="container mt-sm">
    <h1 class='title-lg mb'>
        <%= @questions.count %>
        <%= sklonenie(@questions.count, 'вопрос', 'вопроса','вопросов') %>
    </h1>
</div>
    
<% @questions.each do |question| %>
<div class="mt-sm container">
  <%= render question %>
</div>
<% end %>

app/views/questions/new.html.erb
<div class="container">
    <h2 class="title-lg mb">New question</h2>

    <%= render 'form', question: @question %>
  
</div>

app/views/questions/show.html.erb
<div class="container">
    <h1 class="title-lg mb"> Вопрос</h1>
    <%= render 'question', question: @question %>
    <p class="mt"><%=  link_to "Все вопросы:", questions_path %></p>
</div>

app/views/users/new.html.erb
<div class="container">
    <h2 class="title"> Присоединяйся и спрашивай </h2>

    <div class="mt">
        <%= form_with model: @user do |form| %>
            <p class="mt"><%= form.label :name, 'Введите имя' %></p>
            <p><%= form.text_field :name, class: 'form-text-field' %></p>
            
            <p class="mt"><%= form.label :nickname, 'Введите никнейм' %></p>
            <p><%= form.text_field :nickname, class: 'form-text-field' %></p>
            
            <p class="mt"><%= form.label :email %></p>
            <p><%= form.text_field :email, class: 'form-text-field' %></p>
            
            <p class="mt"><%= form.label :password %></p>
            <p><%= form.password_field :password, class: 'form-text-field' %></p>

            <p class="mt-lg"><%= form.submit 'Зарегистрироваться', class: 'button button-main' %></p>
    
        <% end %>
    </div>

</div>